// Generated by CoffeeScript 1.11.1
(function() {
  var CND, badge, debug, parallel_limit, rpr;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'ASYNC-MINIMAL';

  debug = CND.get_logger('debug', badge);

  this.forever = '../interim/node_modules/async.forever';

  parallel_limit = '../interim/node_modules/run-parallel-limit';

  this.series = function(tasks, handler) {
    return this.parallel(tasks, 1, handler);
  };

  this.parallel = function(tasks, limit, handler) {
    var arity, ref;
    switch (arity = arguments.length) {
      case 2:
        ref = [1, limit], limit = ref[0], handler = ref[1];
        break;
      case 2:
        null;
        break;
      default:
        throw new Error("expected 2 or 3 arguments, got " + arity);
    }
    return parallel_limit(tasks, limit, handler);
  };

}).call(this);

//# sourceMappingURL=main.js.map
