// Generated by CoffeeScript 1.11.1
(function() {
  var CND, alert, badge, debug, echo, forever, help, include, info, log, parallel, ref, rpr, test, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr.bind(CND);

  badge = 'FOREVER-PARALLEL';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  test = require('guy-test');

  ref = require('..'), forever = ref.forever, parallel = ref.parallel;

  this._prune = function() {
    var name, ref1, value;
    ref1 = this;
    for (name in ref1) {
      value = ref1[name];
      if (name.startsWith('_')) {
        continue;
      }
      if (indexOf.call(include, name) < 0) {
        delete this[name];
      }
    }
    return null;
  };

  this._main = function() {
    return test(this, {
      'timeout': 3000
    });
  };

  this["forever (1)"] = function(T, done) {
    var after, get_context;
    after = function(t, handler) {
      whisper("sleeping for " + t + " seconds");
      return setTimeout(handler, t * 1000);
    };
    get_context = function(handler) {
      var count, task;
      count = 10;
      task = function(next) {
        count += -1;
        help(count);
        return after(0.25, function(error) {
          if (count > 0) {
            return next();
          }
          warn('over');
          return handler();
        });
      };
      forever(task);
      return null;
    };
    return debug('44203', get_context(function(error, result) {
      if (error != null) {
        warn(error);
      }
      help(rpr(result));
      return done();
    }));
  };

  if (module.parent == null) {
    include = ["forever (1)"];
    this._prune();
    this._main();
  }

}).call(this);

//# sourceMappingURL=tests.js.map
